### ISSUE TITLE
Keyboard isn't opening while pasting an ID in the search

### ISSUE THREAD

**Issue by Alefev15** [Decathlon/vitamin-compose#155]
**Description**

Since I'm on the search page
When I search by ID
And I pasted a copied ID
Today we have to tap again on the bar to bring up the keyboard and validate the search.

**To Reproduce**

    Steps to reproduce the behaviour:
    1. Copy a product id
    2. Go to the search page
    3. Paste the element
    4. See the keyboard doesn't open
    5. Click again on the search bar to open the keyboard and validate the search.

**Expected behaviour**
The keyboard should be open once the element is pasted into the search bar.

**Smartphone:**

- Device:Android 
- Version [CIS 23.05.01]

**Comment by ManonPolle** [comment]
Hello @Alefev15, Thanks for opening this issue. After looking at it to check the behaviour, we noticed we followed the same behaviour as Material component. 
I close this issue as it is our intention to do that. 
If you have another issue about it, please re open one, but in the [vitamin-android ](https://github.com/Decathlon/vitamin-android/issues)( vitamin xml library ) because I think this is the one used on your screen.
